import { db } from '@/src/services/firebase/config';
import { 
  collection, 
  query, 
  where, 
  getDocs, 
  addDoc, 
  updateDoc, 
  doc, 
  deleteDoc,
  serverTimestamp 
} from 'firebase/firestore';
import { ShoppingItem } from '@/src/models/ShoppingItem';
import { PantryItem } from '@/src/models/PantryItem';
import { logger } from '@/src/utils/logger';

/**
 * Seevia Shopping List Service
 * Handles the lifecycle of shopping needs and auto-generation from pantry alerts.
 */
class ShoppingListService {
  private readonly MODULE = 'SHOPPING_SERVICE';
  private readonly COLLECTION = 'shoppingLists';

  /**
   * Automatically adds a pantry item to the shopping list if it's low on stock.
   */
  async autoAddFromPantry(userId: string, pantryItem: PantryItem): Promise<void> {
    try {
      // Check if item already exists in the shopping list to avoid duplicates
      const exists = await this.checkItemExists(userId, pantryItem.name);
      if (exists) return;

      const newItem: Partial<ShoppingItem> = {
        userId,
        name: pantryItem.name,
        category: pantryItem.category,
        quantity: 1, // Default to 1 unit/pack
        unit: pantryItem.unit,
        isCollected: false,
        autoGenerated: true,
        addedAt: new Date().toISOString(),
      };

      await addDoc(collection(db, this.COLLECTION), newItem);
      logger.info(this.MODULE, `Auto-added ${pantryItem.name} to shopping list.`);
    } catch (error) {
      logger.error(this.MODULE, 'Error in auto-adding item', error);
    }
  }

  /**
   * Fetches the current shopping list for the user.
   */
  async getShoppingList(userId: string): Promise<ShoppingItem[]> {
    const q = query(collection(db, this.COLLECTION), where('userId', '==', userId));
    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as ShoppingItem));
  }

  /**
   * Toggles the collected status (Checking an item off).
   */
  async toggleItemStatus(itemId: string, isCollected: boolean): Promise<void> {
    const itemRef = doc(db, this.COLLECTION, itemId);
    await updateDoc(itemRef, { isCollected });
  }

  /**
   * Clears all collected items from the list.
   */
  async clearCollectedItems(userId: string): Promise<void> {
    const list = await this.getShoppingList(userId);
    const batchPromises = list
      .filter(item => item.isCollected)
      .map(item => deleteDoc(doc(db, this.COLLECTION, item.id)));
    
    await Promise.all(batchPromises);
  }

  private async checkItemExists(userId: string, name: string): Promise<boolean> {
    const q = query(
      collection(db, this.COLLECTION), 
      where('userId', '==', userId), 
      where('name', '==', name),
      where('isCollected', '==', false)
    );
    const snapshot = await getDocs(q);
    return !snapshot.empty;
  }
}

export const shoppingListService = new ShoppingListService();
