import { db } from '@/src/services/firebase/config';
import { 
  collection, 
  query, 
  where, 
  getDocs, 
  addDoc, 
  updateDoc, 
  doc, 
  deleteDoc,
  serverTimestamp 
} from 'firebase/firestore';
import { ShoppingItem } from '@/src/models/ShoppingItem';
import { PantryItem } from '@/src/models/PantryItem';
import { ExpiryService } from './expiry.service';
import { PantryService } from './pantry.service';
import hapticService from '@/src/services/common/haptic.service';
import { logger } from '@/src/utils/logger';

/**
 * Seevia Shopping List Service
 * Manages automated replenishment and manual shopping needs.
 */
export class ShoppingListService {
  private static readonly MODULE = 'SHOPPING_SERVICE';
  private static readonly COLLECTION = 'shoppingLists';

  /**
   * Automatically adds a pantry item to the shopping list.
   * Triggered by Expiry alerts or Low-Stock checks.
   */
  static async autoAddFromPantry(userId: string, item: PantryItem, reason: string): Promise<void> {
    try {
      const exists = await this.checkItemExists(userId, item.name);
      if (exists) return;

      const newItem: Partial<ShoppingItem> = {
        userId,
        name: item.name,
        category: item.category,
        quantity: 1,
        unit: item.unit,
        isCollected: false,
        autoGenerated: true,
        reason: reason as any,
        addedAt: new Date().toISOString(),
      };

      await addDoc(collection(db, this.COLLECTION), newItem);
      logger.info(this.MODULE, `Auto-added ${item.name} due to ${reason}`);
    } catch (error) {
      logger.error(this.MODULE, 'Error in auto-adding item', error);
    }
  }

  /**
   * Fetches the shopping list from Firestore.
   */
  static async getShoppingList(userId: string): Promise<ShoppingItem[]> {
    const q = query(collection(db, this.COLLECTION), where('userId', '==', userId));
    const snapshot = await getDocs(q);
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as ShoppingItem));
  }

  /**
   * Toggles 'Collected' status with tactile feedback for the user.
   */
  static async toggleItemStatus(itemId: string, isCollected: boolean): Promise<void> {
    const itemRef = doc(db, this.COLLECTION, itemId);
    await updateDoc(itemRef, { isCollected });
    if (isCollected) await hapticService.success();
  }

  /**
   * Formats the list for the Voice Assistant's briefing.
   */
  static formatForVoice(shoppingList: ShoppingItem[]): string {
    if (shoppingList.length === 0) {
      return 'Your shopping list is currently empty.';
    }
    const uncollected = shoppingList.filter(i => !i.isCollected);
    const itemNames = uncollected.map(item => item.name).join(', ');
    return `You have ${uncollected.length} items to buy, including: ${itemNames}.`;
  }

  private static async checkItemExists(userId: string, name: string): Promise<boolean> {
    const q = query(
      collection(db, this.COLLECTION), 
      where('userId', '==', userId), 
      where('name', '==', name),
      where('isCollected', '==', false)
    );
    const snapshot = await getDocs(q);
    return !snapshot.empty;
  }
}
