import { PantryCategory } from './PantryItem';

/**
 * Seevia Shopping List Model
 * Optimized for PWD store navigation and budgeting.
 */
export interface ShoppingItem {
  id: string;
  userId: string;
  name: string;
  category: PantryCategory;
  quantity: number;
  unit: string;
  
  // Store Logic
  isCollected: boolean;
  aisleNumber?: string; // For Module 5: Indoor Navigation
  estimatedPrice?: number; // In PKR or AED
  
  // Metadata
  addedAt: string;
  autoGenerated: boolean; // True if added by the Smart Pantry "Low Stock" logic
}
